### ISSUE TITLE
Invalid format error of sumo-kgen

### ISSUE THREAD

**Issue by sajidurehman** [ajjackson/castep-sumo-tutorial#1]
Hi Adam,
           I am trying to generate KPOINTS for Si. But i am facing following error. Could you please guide me to fix this error.
Command : sumo-kgen -c castep -p Si2-out.cell

Structure information:
	Space group number: 227
	International symbol: Fd-3m
	Lattice type: cubic

k-point path:
	\Gamma -> L -> W -> X -> \Gamma

k-points:
	\Gamma: 0.0 0.0 0.0
	L: 0.5 0.5 0.5
	W: 0.5 0.25 0.75
	X: 0.5 0.0 0.5

k-point label indices:
	\Gamma: 1
	L: 62
	W: 112
	X: 147
	\Gamma: 217
Traceback (most recent call last):
  File "/home/max/.local/bin/sumo-kgen", line 11, in <module>
    load_entry_point('sumo', 'console_scripts', 'sumo-kgen')()
  File "/home/max/sumo/sumo/cli/kgen.py", line 307, in main
    phonon=args.phonon)
  File "/home/max/sumo/sumo/cli/kgen.py", line 164, in kgen
    kpath.prim.to(filename=prim_filename)
  File "/home/max/.local/lib/python3.6/site-packages/pymatgen/core/structure.py", line 2174, in to
    raise ValueError("Invalid format: `%s`" % str(fmt))
ValueError: Invalid format:

**Comment by ajjackson** [comment]
Sorry for slow response; I will be back at work next week

**Comment by sajidurehman** [comment]
Thank you for reply. I will wait for you.

**Comment by ajjackson** [comment]
Right, I think I see the problem. This is a bug/oversight. We should consider restructuring things to make this kind of oversight harder. But first I will fix it!

**Comment by sajidurehman** [comment]
Thank you @ajjackson for fixing this bug. I will wait for your postive response.

**Comment by ajjackson** [comment]
Could you try out the fix on the https://github.com/SMTG-UCL/sumo/tree/castep-kgen-prim branch?

**Comment by sajidurehman** [comment]
Hi Adam,
             First I uninstall the sumo by pip3 uninstall sumo
Then again downloaded and installed by following commands 
git clone https://github.com/smtg-ucl/sumo.git
cd sumo
pip3 install --user -e .

Then tried the sumo-kgen -c castep -p Si2-out.cell command. But again got the same error. 
Is that right way ?

**Comment by ajjackson** [comment]
You're nearly there! You need to change to the feature branch. Because you already installed with `-e`, you should be able to `cd sumo` and `git checkout castep-kgen-prim` without reinstalling.

**Comment by sajidurehman** [comment]
Thank you for guidance and fixing the bug. Now successfully got the band.cell file. 
for optimized file (Si2-out.cell) it run smoothly.  But when I used for unoptimized file (Si2.cell) got the follwoing error.
Command : sumo-kgen --code castep -p Si2.cell
Error:
Traceback (most recent call last):
  File "/home/max/.local/bin/sumo-kgen", line 11, in <module>
    load_entry_point('sumo', 'console_scripts', 'sumo-kgen')()
  File "/home/max/sumo/sumo/cli/kgen.py", line 310, in main
    phonon=args.phonon)
  File "/home/max/sumo/sumo/cli/kgen.py", line 136, in kgen
    structure = CastepCell.from_file(filename).structure
  File "/home/max/sumo/sumo/io/castep.py", line 112, in structure
    raise ValueError("Couldn't find any atom positions in cell file")
ValueError: Couldn't find any atom positions in cell file

**Comment by ajjackson** [comment]
Can you post the .cell file? The parser is having trouble reading it.

**Comment by sajidurehman** [comment]
Sorry for inconvenience. Again, I have checked for different .cell files its generating band.cell file without any error.  If I face again this error I will post with .cell file.  Once again thank you for fixing bug.
